name: Run Python Script

on:
  schedule:
    - cron: "30 2 * * *"   # 08:00 AM IST
    - cron: "5 9 * * *"    # 02:35 PM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Auto-fix formatting
        run: |
          pip install autopep8
          autopep8 --in-place --aggressive --aggressive myscript.py

      - name: Run Python script
        run: python myscript.py
