name: Run Python Script

on:
  schedule:
    # Run at 08:00 IST (02:30 UTC)
    - cron: '30 2 * * 1-5'
    # Run at 02:30 PM IST (09:00 UTC)
    - cron: '0 9 * * 1-5'
  workflow_dispatch:  # allows manual trigger from Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python myscript.py
